import type { ComingSoonPack } from "./types";

export const accountsReceivablePack: ComingSoonPack = {
  kpis: [
    {
      title: "Outstanding AR",
      value: "$84,200",
      delta: "+8.2%",
      footnote: "Invoices awaiting payment",
    },
    {
      title: "Collected (30d)",
      value: "$62,450",
      delta: "+15.1%",
      footnote: "Collections trending up",
    },
    {
      title: "Overdue invoices",
      value: "37",
      delta: "+4.0%",
      footnote: "Aging needs attention",
    },
    {
      title: "DSO",
      value: "42 days",
      delta: "-3.5%",
      footnote: "Days sales outstanding improved",
    },
  ],
  chartTitle: "Collections",
  chart: {
    "3m": [
      { label: "May 4", value: 12400 },
      { label: "May 11", value: 13850 },
      { label: "May 18", value: 11920 },
      { label: "May 25", value: 15210 },
      { label: "Jun 1", value: 14780 },
      { label: "Jun 8", value: 16340 },
      { label: "Jun 15", value: 15890 },
      { label: "Jun 22", value: 17120 },
      { label: "Jun 29", value: 16950 },
      { label: "Jul 6", value: 18400 },
      { label: "Jul 13", value: 17660 },
      { label: "Jul 20", value: 19210 },
    ],
    "30d": [
      { label: "Jul 1", value: 1840 },
      { label: "Jul 4", value: 2105 },
      { label: "Jul 7", value: 1670 },
      { label: "Jul 10", value: 2280 },
      { label: "Jul 13", value: 2410 },
      { label: "Jul 16", value: 2195 },
      { label: "Jul 19", value: 2560 },
      { label: "Jul 22", value: 2730 },
      { label: "Jul 25", value: 2485 },
      { label: "Jul 28", value: 2810 },
    ],
    "7d": [
      { label: "Mon", value: 920 },
      { label: "Tue", value: 1105 },
      { label: "Wed", value: 870 },
      { label: "Thu", value: 1240 },
      { label: "Fri", value: 1380 },
      { label: "Sat", value: 310 },
      { label: "Sun", value: 180 },
    ],
  },
  tableColumns: {
    name: "Invoice",
    category: "Customer",
    status: "Status",
    metric: "Amount",
    owner: "Owner",
  },
  tableRows: [
    {
      name: "INV-1042",
      category: "Northwind Labs",
      status: "Paid",
      metric: "$4,800",
      owner: "Maya Chen",
    },
    {
      name: "INV-1043",
      category: "Brightline Studio",
      status: "Open",
      metric: "$1,250",
      owner: "Jordan Hale",
    },
    {
      name: "INV-1044",
      category: "Cedar & Co",
      status: "Overdue",
      metric: "$640",
      owner: "Priya Nair",
    },
    {
      name: "INV-1045",
      category: "Orbit Freight",
      status: "Paid",
      metric: "$8,900",
      owner: "Alex Ruiz",
    },
    {
      name: "INV-1046",
      category: "Maple Health",
      status: "Open",
      metric: "$2,410",
      owner: "Sam Okonkwo",
    },
    {
      name: "INV-1047",
      category: "Peak Analytics",
      status: "Paid",
      metric: "$12,200",
      owner: "Riley Cho",
    },
    {
      name: "INV-1048",
      category: "Harbor Books",
      status: "Overdue",
      metric: "$390",
      owner: "Casey Nguyen",
    },
    {
      name: "INV-1049",
      category: "Lumen Legal",
      status: "Open",
      metric: "$1,875",
      owner: "Dana Brooks",
    },
    {
      name: "INV-1050",
      category: "Atlas Robotics",
      status: "Paid",
      metric: "$6,450",
      owner: "Elena Voss",
    },
    {
      name: "INV-1051",
      category: "Fern Kitchen",
      status: "Overdue",
      metric: "$275",
      owner: "Omar Farid",
    },
    {
      name: "INV-1052",
      category: "Quartz Media",
      status: "Open",
      metric: "$1,620",
      owner: "Tess Park",
    },
    {
      name: "INV-1053",
      category: "Silverline Bank",
      status: "Paid",
      metric: "$18,000",
      owner: "Noah Kim",
    },
    {
      name: "INV-1054",
      category: "Drift Apparel",
      status: "Open",
      metric: "$880",
      owner: "Luca Rossi",
    },
    {
      name: "INV-1055",
      category: "Helix Biotech",
      status: "Paid",
      metric: "$5,100",
      owner: "Amina Shah",
    },
    {
      name: "INV-1056",
      category: "Compass Travel",
      status: "Overdue",
      metric: "$2,040",
      owner: "Ben Walsh",
    },
    {
      name: "INV-1057",
      category: "Night Owl Games",
      status: "Open",
      metric: "$720",
      owner: "Chloe Berg",
    },
    {
      name: "INV-1058",
      category: "Summit HR",
      status: "Paid",
      metric: "$1,330",
      owner: "Drew Patel",
    },
    {
      name: "INV-1059",
      category: "Polar Logistics",
      status: "Open",
      metric: "$7,650",
      owner: "Harper Liu",
    },
    {
      name: "INV-1060",
      category: "Willow Schools",
      status: "Paid",
      metric: "$540",
      owner: "Ivy Grant",
    },
    {
      name: "INV-1061",
      category: "Nimbus Cloud",
      status: "Paid",
      metric: "$9,870",
      owner: "Jules Ortega",
    },
    {
      name: "INV-1062",
      category: "Ember Coffee",
      status: "Overdue",
      metric: "$210",
      owner: "Kai Bennett",
    },
    {
      name: "INV-1063",
      category: "Redwood Insurance",
      status: "Open",
      metric: "$3,460",
      owner: "Lane Cooper",
    },
    {
      name: "INV-1064",
      category: "Volt Energy",
      status: "Paid",
      metric: "$11,300",
      owner: "Mira Solis",
    },
    {
      name: "INV-1065",
      category: "Canvas Design",
      status: "Open",
      metric: "$1,140",
      owner: "Nico Adler",
    },
  ],
};
