import type { ComingSoonPack } from "./types";

export const saasAnalyticsPack: ComingSoonPack = {
  kpis: [
    {
      title: "MRR",
      value: "$12,450",
      delta: "+12.5%",
      footnote: "Trending up this month",
    },
    {
      title: "New sign-ups",
      value: "1,234",
      delta: "-20%",
      footnote: "Acquisition needs attention",
    },
    {
      title: "Active users",
      value: "45,678",
      delta: "+12.5%",
      footnote: "Strong retention",
    },
    {
      title: "Growth rate",
      value: "4.5%",
      delta: "+4.5%",
      footnote: "Steady performance",
    },
  ],
  chartTitle: "Total visitors",
  chart: {
    "3m": [
      { label: "May 4", value: 1820 },
      { label: "May 11", value: 1940 },
      { label: "May 18", value: 2010 },
      { label: "May 25", value: 1880 },
      { label: "Jun 1", value: 2150 },
      { label: "Jun 8", value: 2280 },
      { label: "Jun 15", value: 2210 },
      { label: "Jun 22", value: 2400 },
      { label: "Jun 29", value: 2350 },
      { label: "Jul 6", value: 2520 },
      { label: "Jul 13", value: 2480 },
      { label: "Jul 20", value: 2610 },
    ],
    "30d": [
      { label: "Jul 1", value: 210 },
      { label: "Jul 4", value: 245 },
      { label: "Jul 7", value: 198 },
      { label: "Jul 10", value: 260 },
      { label: "Jul 13", value: 272 },
      { label: "Jul 16", value: 255 },
      { label: "Jul 19", value: 290 },
      { label: "Jul 22", value: 305 },
      { label: "Jul 25", value: 288 },
      { label: "Jul 28", value: 318 },
    ],
    "7d": [
      { label: "Mon", value: 240 },
      { label: "Tue", value: 255 },
      { label: "Wed", value: 230 },
      { label: "Thu", value: 270 },
      { label: "Fri", value: 290 },
      { label: "Sat", value: 180 },
      { label: "Sun", value: 165 },
    ],
  },
  tableColumns: {
    name: "Plan",
    category: "Segment",
    status: "Status",
    metric: "Seats",
    owner: "Owner",
  },
  tableRows: [
    {
      name: "Northwind Labs",
      category: "Enterprise",
      status: "Active",
      metric: "240",
      owner: "Maya Chen",
    },
    {
      name: "Brightline Studio",
      category: "Growth",
      status: "Trial",
      metric: "18",
      owner: "Jordan Hale",
    },
    { name: "Cedar & Co", category: "Starter", status: "Active", metric: "8", owner: "Priya Nair" },
    {
      name: "Orbit Freight",
      category: "Enterprise",
      status: "Churned",
      metric: "90",
      owner: "Alex Ruiz",
    },
    {
      name: "Maple Health",
      category: "Growth",
      status: "Active",
      metric: "42",
      owner: "Sam Okonkwo",
    },
    {
      name: "Peak Analytics",
      category: "Enterprise",
      status: "Active",
      metric: "310",
      owner: "Riley Cho",
    },
    {
      name: "Harbor Books",
      category: "Starter",
      status: "Trial",
      metric: "5",
      owner: "Casey Nguyen",
    },
    {
      name: "Lumen Legal",
      category: "Growth",
      status: "Active",
      metric: "27",
      owner: "Dana Brooks",
    },
    {
      name: "Atlas Robotics",
      category: "Enterprise",
      status: "Active",
      metric: "180",
      owner: "Elena Voss",
    },
    {
      name: "Fern Kitchen",
      category: "Starter",
      status: "Churned",
      metric: "4",
      owner: "Omar Farid",
    },
    { name: "Quartz Media", category: "Growth", status: "Trial", metric: "22", owner: "Tess Park" },
    {
      name: "Silverline Bank",
      category: "Enterprise",
      status: "Active",
      metric: "500",
      owner: "Noah Kim",
    },
    {
      name: "Drift Apparel",
      category: "Starter",
      status: "Active",
      metric: "12",
      owner: "Luca Rossi",
    },
    {
      name: "Helix Biotech",
      category: "Enterprise",
      status: "Trial",
      metric: "75",
      owner: "Amina Shah",
    },
    {
      name: "Compass Travel",
      category: "Growth",
      status: "Active",
      metric: "33",
      owner: "Ben Walsh",
    },
    {
      name: "Night Owl Games",
      category: "Starter",
      status: "Trial",
      metric: "9",
      owner: "Chloe Berg",
    },
    { name: "Summit HR", category: "Growth", status: "Churned", metric: "16", owner: "Drew Patel" },
    {
      name: "Polar Logistics",
      category: "Enterprise",
      status: "Active",
      metric: "220",
      owner: "Harper Liu",
    },
    {
      name: "Willow Schools",
      category: "Starter",
      status: "Active",
      metric: "6",
      owner: "Ivy Grant",
    },
    {
      name: "Nimbus Cloud",
      category: "Enterprise",
      status: "Active",
      metric: "410",
      owner: "Jules Ortega",
    },
    {
      name: "Ember Coffee",
      category: "Starter",
      status: "Trial",
      metric: "3",
      owner: "Kai Bennett",
    },
    {
      name: "Redwood Insurance",
      category: "Growth",
      status: "Active",
      metric: "54",
      owner: "Lane Cooper",
    },
    {
      name: "Volt Energy",
      category: "Enterprise",
      status: "Churned",
      metric: "140",
      owner: "Mira Solis",
    },
    {
      name: "Canvas Design",
      category: "Growth",
      status: "Trial",
      metric: "19",
      owner: "Nico Adler",
    },
  ],
};
