import type { ComingSoonPack } from "./types";

export const shadcnClassicPack: ComingSoonPack = {
  kpis: [
    {
      title: "Total Revenue",
      value: "$1,250.00",
      delta: "+12.5%",
      footnote: "Trending up this month",
    },
    {
      title: "New Customers",
      value: "1,234",
      delta: "-20%",
      footnote: "Acquisition needs attention",
    },
    {
      title: "Active Accounts",
      value: "45,678",
      delta: "+12.5%",
      footnote: "Strong user retention",
    },
    {
      title: "Growth Rate",
      value: "4.5%",
      delta: "+4.5%",
      footnote: "Steady performance",
    },
  ],
  chartTitle: "Total visitors",
  chart: {
    "3m": [
      { label: "May 4", value: 1250 },
      { label: "May 11", value: 1480 },
      { label: "May 18", value: 1390 },
      { label: "May 25", value: 1620 },
      { label: "Jun 1", value: 1710 },
      { label: "Jun 8", value: 1580 },
      { label: "Jun 15", value: 1840 },
      { label: "Jun 22", value: 1920 },
      { label: "Jun 29", value: 1860 },
      { label: "Jul 6", value: 2050 },
      { label: "Jul 13", value: 1980 },
      { label: "Jul 20", value: 2140 },
    ],
    "30d": [
      { label: "Jul 1", value: 86 },
      { label: "Jul 4", value: 92 },
      { label: "Jul 7", value: 78 },
      { label: "Jul 10", value: 101 },
      { label: "Jul 13", value: 97 },
      { label: "Jul 16", value: 110 },
      { label: "Jul 19", value: 104 },
      { label: "Jul 22", value: 118 },
      { label: "Jul 25", value: 121 },
      { label: "Jul 28", value: 115 },
    ],
    "7d": [
      { label: "Mon", value: 42 },
      { label: "Tue", value: 51 },
      { label: "Wed", value: 47 },
      { label: "Thu", value: 58 },
      { label: "Fri", value: 63 },
      { label: "Sat", value: 29 },
      { label: "Sun", value: 24 },
    ],
  },
  tableColumns: {
    name: "Header",
    category: "Section type",
    status: "Status",
    metric: "Target",
    owner: "Reviewer",
  },
  tableRows: [
    {
      name: "Cover page",
      category: "Cover page",
      status: "In Process",
      metric: "18",
      owner: "Eddie Lake",
    },
    {
      name: "Table of contents",
      category: "Table of contents",
      status: "Done",
      metric: "29",
      owner: "Eddie Lake",
    },
    {
      name: "Executive summary",
      category: "Narrative",
      status: "Done",
      metric: "10",
      owner: "Eddie Lake",
    },
    {
      name: "Technical approach",
      category: "Narrative",
      status: "Done",
      metric: "27",
      owner: "Jamik Tashpulatov",
    },
    {
      name: "Design",
      category: "Narrative",
      status: "In Process",
      metric: "2",
      owner: "Jamik Tashpulatov",
    },
    {
      name: "Capabilities",
      category: "Narrative",
      status: "In Process",
      metric: "20",
      owner: "Jamik Tashpulatov",
    },
    {
      name: "Integration",
      category: "Narrative",
      status: "In Process",
      metric: "12",
      owner: "Jamik Tashpulatov",
    },
    {
      name: "Innovation",
      category: "Narrative",
      status: "Done",
      metric: "8",
      owner: "Assign reviewer",
    },
    {
      name: "EMR overview",
      category: "Technical content",
      status: "Done",
      metric: "15",
      owner: "Assign reviewer",
    },
    {
      name: "Advanced algorithms",
      category: "Narrative",
      status: "In Review",
      metric: "11",
      owner: "Assign reviewer",
    },
    {
      name: "Security model",
      category: "Technical content",
      status: "In Review",
      metric: "22",
      owner: "Eddie Lake",
    },
    {
      name: "Staffing plan",
      category: "Narrative",
      status: "Done",
      metric: "6",
      owner: "Eddie Lake",
    },
    {
      name: "Past performance",
      category: "Narrative",
      status: "In Process",
      metric: "14",
      owner: "Jamik Tashpulatov",
    },
    {
      name: "Key personnel",
      category: "Narrative",
      status: "Done",
      metric: "9",
      owner: "Jamik Tashpulatov",
    },
    {
      name: "Focus documents",
      category: "Technical content",
      status: "In Review",
      metric: "17",
      owner: "Eddie Lake",
    },
    {
      name: "Quality plan",
      category: "Narrative",
      status: "In Process",
      metric: "5",
      owner: "Assign reviewer",
    },
    {
      name: "Risk register",
      category: "Technical content",
      status: "Done",
      metric: "13",
      owner: "Eddie Lake",
    },
    {
      name: "Timeline",
      category: "Narrative",
      status: "In Process",
      metric: "21",
      owner: "Jamik Tashpulatov",
    },
    {
      name: "Budget notes",
      category: "Narrative",
      status: "In Review",
      metric: "7",
      owner: "Assign reviewer",
    },
    {
      name: "Appendix A",
      category: "Technical content",
      status: "Done",
      metric: "4",
      owner: "Eddie Lake",
    },
    {
      name: "Appendix B",
      category: "Technical content",
      status: "In Process",
      metric: "16",
      owner: "Jamik Tashpulatov",
    },
    { name: "Glossary", category: "Narrative", status: "Done", metric: "3", owner: "Eddie Lake" },
    {
      name: "References",
      category: "Narrative",
      status: "In Review",
      metric: "19",
      owner: "Assign reviewer",
    },
    {
      name: "Signatures",
      category: "Cover page",
      status: "In Process",
      metric: "1",
      owner: "Eddie Lake",
    },
  ],
};
