import type { ComingSoonPack } from "./types";

export const sportTeamsPack: ComingSoonPack = {
  kpis: [
    {
      title: "Roster size",
      value: "248",
      delta: "+6.0%",
      footnote: "Players across all squads",
    },
    {
      title: "Active teams",
      value: "18",
      delta: "+2",
      footnote: "Two new squads this season",
    },
    {
      title: "Upcoming games",
      value: "12",
      delta: "-8.0%",
      footnote: "Lighter week on the calendar",
    },
    {
      title: "Win rate",
      value: "62%",
      delta: "+4.5%",
      footnote: "Above conference average",
    },
  ],
  chartTitle: "Attendance",
  chart: {
    "3m": [
      { label: "May 4", value: 4200 },
      { label: "May 11", value: 4680 },
      { label: "May 18", value: 3910 },
      { label: "May 25", value: 5120 },
      { label: "Jun 1", value: 4870 },
      { label: "Jun 8", value: 5340 },
      { label: "Jun 15", value: 5010 },
      { label: "Jun 22", value: 5580 },
      { label: "Jun 29", value: 5420 },
      { label: "Jul 6", value: 5790 },
      { label: "Jul 13", value: 5610 },
      { label: "Jul 20", value: 6040 },
    ],
    "30d": [
      { label: "Jul 1", value: 890 },
      { label: "Jul 4", value: 1120 },
      { label: "Jul 7", value: 760 },
      { label: "Jul 10", value: 980 },
      { label: "Jul 13", value: 1040 },
      { label: "Jul 16", value: 870 },
      { label: "Jul 19", value: 1210 },
      { label: "Jul 22", value: 990 },
      { label: "Jul 25", value: 1150 },
      { label: "Jul 28", value: 1280 },
    ],
    "7d": [
      { label: "Mon", value: 0 },
      { label: "Tue", value: 420 },
      { label: "Wed", value: 0 },
      { label: "Thu", value: 680 },
      { label: "Fri", value: 910 },
      { label: "Sat", value: 1450 },
      { label: "Sun", value: 1220 },
    ],
  },
  tableColumns: {
    name: "Team",
    category: "Division",
    status: "Status",
    metric: "Record",
    owner: "Coach",
  },
  tableRows: [
    {
      name: "Harbor Hawks",
      category: "East",
      status: "In season",
      metric: "12-4",
      owner: "Pat Riley",
    },
    {
      name: "Cedar Wolves",
      category: "North",
      status: "In season",
      metric: "9-7",
      owner: "Kim Alvarez",
    },
    {
      name: "Orbit Comets",
      category: "West",
      status: "Preseason",
      metric: "0-0",
      owner: "Lee Park",
    },
    {
      name: "Maple Bears",
      category: "North",
      status: "In season",
      metric: "11-5",
      owner: "Chris Donovan",
    },
    {
      name: "Peak Rangers",
      category: "West",
      status: "In season",
      metric: "8-8",
      owner: "Taylor Quinn",
    },
    {
      name: "Lumen Foxes",
      category: "East",
      status: "Offseason",
      metric: "6-10",
      owner: "Jordan Blake",
    },
    {
      name: "Atlas Titans",
      category: "South",
      status: "In season",
      metric: "14-2",
      owner: "Samira Cole",
    },
    {
      name: "Fern Otters",
      category: "East",
      status: "Preseason",
      metric: "0-0",
      owner: "Noah Ellis",
    },
    {
      name: "Quartz Lynx",
      category: "West",
      status: "In season",
      metric: "10-6",
      owner: "Avery Stone",
    },
    {
      name: "Silverline Sharks",
      category: "South",
      status: "In season",
      metric: "7-9",
      owner: "Morgan Wade",
    },
    {
      name: "Drift Falcons",
      category: "North",
      status: "Offseason",
      metric: "5-11",
      owner: "Casey Flint",
    },
    {
      name: "Helix Stallions",
      category: "South",
      status: "In season",
      metric: "13-3",
      owner: "Riley Brooks",
    },
    {
      name: "Compass Gulls",
      category: "East",
      status: "Preseason",
      metric: "0-0",
      owner: "Dana Shore",
    },
    {
      name: "Night Owl Owls",
      category: "West",
      status: "In season",
      metric: "9-7",
      owner: "Quinn Marsh",
    },
    {
      name: "Summit Elk",
      category: "North",
      status: "In season",
      metric: "11-5",
      owner: "Harper Frost",
    },
    {
      name: "Polar Ice",
      category: "North",
      status: "Offseason",
      metric: "4-12",
      owner: "Blake North",
    },
    {
      name: "Willow Sparrows",
      category: "East",
      status: "In season",
      metric: "8-8",
      owner: "Ivy Grant",
    },
    {
      name: "Nimbus Eagles",
      category: "West",
      status: "In season",
      metric: "12-4",
      owner: "Jules Ortega",
    },
    {
      name: "Ember Sparks",
      category: "South",
      status: "Preseason",
      metric: "0-0",
      owner: "Kai Bennett",
    },
    {
      name: "Redwood Giants",
      category: "West",
      status: "In season",
      metric: "10-6",
      owner: "Lane Cooper",
    },
    {
      name: "Volt Bolts",
      category: "South",
      status: "In season",
      metric: "15-1",
      owner: "Mira Solis",
    },
    {
      name: "Canvas Coyotes",
      category: "East",
      status: "Offseason",
      metric: "3-13",
      owner: "Nico Adler",
    },
    {
      name: "Harbor Juniors",
      category: "East",
      status: "Preseason",
      metric: "0-0",
      owner: "Pat Riley",
    },
    {
      name: "Cedar Reserves",
      category: "North",
      status: "In season",
      metric: "7-9",
      owner: "Kim Alvarez",
    },
  ],
};
